/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.94
 * Generated at: 2024-02-12 06:21:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1704619385681L));
    _jspx_dependants.put("jar:file:/C:/Class/NoSmoking/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/noSmoking/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"/smoking/resources/css/common/main.css\">\r\n");
      out.write("	<!-- jQuery library -->\r\n");
      out.write("	<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("	<script src=\"/smoking/resources/js/common/main.js\"></script>\r\n");
      out.write("	<script src=\"/smoking/resources/js/common/mainAjax.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\"productRefesh(), noSmoking()\">\r\n");
      out.write("\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "common/header.jsp", out, false);
      out.write("\r\n");
      out.write("	<div class=\"smoking\">\r\n");
      out.write("        \r\n");
      out.write("        <span class=\"slideshow-container\">\r\n");
      out.write("            <div class=\"Slidesbackground\">\r\n");
      out.write("               <div class=\"mySlides fade\">\r\n");
      out.write("               <img src=\"./resources/img/main/광고.jpg\" class=\"slideshow-image\">\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"mySlides fade\">\r\n");
      out.write("                   <img src=\"./resources/img/main/광고1.jpg\" class=\"slideshow-image\">\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"mySlides fade\">\r\n");
      out.write("                   <img src=\"./resources/img/main/광고2.jpeg\" class=\"slideshow-image\">\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"mySlides fade\">\r\n");
      out.write("                   <img src=\"./resources/img/main/광고3.jpeg\" class=\"slideshow-image\">\r\n");
      out.write("               </div> \r\n");
      out.write("           </div>\r\n");
      out.write("        </span>\r\n");
      out.write("\r\n");
      out.write("        <br><br><br>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"aaa\">\r\n");
      out.write("            <div class=\"promotion22\">\r\n");
      out.write("                <span>금연 서비스</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"aaa\">\r\n");
      out.write("            <div class=\"promotion-div\">\r\n");
      out.write("                <div class=\"theme\">\r\n");
      out.write("	                <a href=\"searchHospital.ho\">\r\n");
      out.write("	                    <div class=\"sumnali\">\r\n");
      out.write("	                        <img src=\"./resources/img/main/보건소.png\" alt=\"\" class=\"sumnali-img\">\r\n");
      out.write("	                    </div>\r\n");
      out.write("	                    <div class=\"sumnali-title\">\r\n");
      out.write("	                                                금연 할꺼면 <br> 보건소 찾으러 가자\r\n");
      out.write("	                    </div>\r\n");
      out.write("	                </a>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"theme\">\r\n");
      out.write("	                <a href=\"productList.pr\">\r\n");
      out.write("	                    <div class=\"sumnali\">\r\n");
      out.write("	                        <img src=\"./resources/img/main/영상시청.png\" alt=\"\" class=\"sumnali-img\">\r\n");
      out.write("	                    </div>\r\n");
      out.write("	                    <div class=\"sumnali-title\">\r\n");
      out.write("	                        	영상으로도<br> 흡연을 예방할 수 있어\r\n");
      out.write("	                    </div>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"theme\">\r\n");
      out.write("	                <a href=\"writer.me\">\r\n");
      out.write("	                    <div class=\"sumnali\">\r\n");
      out.write("	                        <img src=\"./resources/img/main/free-icon-contract-5987273.png\" alt=\"\" class=\"sumnali-img\">\r\n");
      out.write("	                    </div>\r\n");
      out.write("	                    <div class=\"sumnali-title\">\r\n");
      out.write("	                       	 금연 신청을<br> 해야 금연에 성공을<br>할 수 있어\r\n");
      out.write("	                    </div>	\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div><br><br>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"boss-view-img\">\r\n");
      out.write("            <div class=\"video\">\r\n");
      out.write("                <div class=\"promotion22\">\r\n");
      out.write("                    <img src=\"./resources/img/main/편의점.png\" class=\"market-img\">\r\n");
      out.write("                    <span>금연 상품</span>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"no1\" >\r\n");
      out.write("                    <div id=\"smoke\" class=\"smoke\">\r\n");
      out.write("                        <img src=\"/NoSmoking/img/광고2.jpeg\" alt=\"\" class=\"img-1\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            \r\n");
      out.write("                <div class=\"bbb\">\r\n");
      out.write("                    <div id=\"title-text\" class=\"title-text\">\r\n");
      out.write("                        <h2 class=\"text-pom22\">안녕하세요</h2>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"boss-view-img\">\r\n");
      out.write("            <div class=\"challenge\">\r\n");
      out.write("                <div class=\"challenge-theme\" id=\"smoking\">\r\n");
      out.write("                    <div class=\"challenge-title\">\r\n");
      out.write("                        올해 금연 도전자\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"challenge-title\">\r\n");
      out.write("                        50 명\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"challenge-theme\">\r\n");
      out.write("                    <div class=\"challenge-title\">\r\n");
      out.write("                        올해 금연 성공자\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"challenge-title\">\r\n");
      out.write("                        5 명\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
