/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.94
 * Generated at: 2024-01-23 10:36:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("	<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN\" crossorigin=\"anonymous\">\r\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.7.1.js\" integrity=\"sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("	<script src=\"resources/js/member/memberJs/member.js\"></script>\r\n");
      out.write("	<link rel=\"stylesheet\" href=\"/smoking/resources/css/member/login.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"login-header\" align=\"center\">\r\n");
      out.write("        <a href=\"main.me\"><img src=\"./resources/img/main/금연프로젝트.png\"></a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("	 <div class=\"login-main\">\r\n");
      out.write("        <form action=\"loginMember.me\" method=\"post\">\r\n");
      out.write("            <div class=\"login-middle\">\r\n");
      out.write("                <div class=\"form-floating mb-3\">\r\n");
      out.write("                    <input type=\"text\" class=\"form-control id\" id=\"floatingInput\" name=\"userId\" placeholder=\"name@example.com\">\r\n");
      out.write("                    <label for=\"floatingInput\">아이디 또는 이메일</label>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"form-floating\">\r\n");
      out.write("                    <input type=\"password\" class=\"form-control\" id=\"floatingPassword\" name=\"userPwd\" placeholder=\"Password\">\r\n");
      out.write("                    <label for=\"floatingPassword\">비밀번호</label>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"login-footer\">\r\n");
      out.write("                <div class=\"checkbox-wrapper-1 save-id\">\r\n");
      out.write("                    <input id=\"example-1\" class=\"substituted\" type=\"checkbox\" aria-hidden=\"true\" />\r\n");
      out.write("                    <label for=\"example-1\">아이디 저장</label>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"d-grid gap-2 login-btn-div\" >\r\n");
      out.write("                    <button class=\"btn btn-primary\" id=\"login-btn\" type=\"submit\">login</button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div align=\"center\" class=\"find-join-area\">\r\n");
      out.write("                    <div class=\"login-find-User\" data-bs-toggle=\"modal\" data-bs-target=\"#exampleModal\">아이디/비밀번호 찾기</div>\r\n");
      out.write("                    <div class=\"login-join\" onclick=\"location.href ='insertMember.me'\">회원가입</div>\r\n");
      out.write("                </div>\r\n");
      out.write("             </div>\r\n");
      out.write("        </form>\r\n");
      out.write("   \r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- 아이디 비밀번로 찾기 모달 -->\r\n");
      out.write("    <div class=\"modal fade\" id=\"exampleModal\" tabindex=\"-1\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("        <div class=\"modal-dialog\">\r\n");
      out.write("          <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("                <div>\r\n");
      out.write("                    <h1>아이디 비밀번호 찾기</h1>\r\n");
      out.write("                    <p class=\"modal-font\">휴대폰 인증을 하면 회원가입된 아이디를 알려드려요</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("             </div>\r\n");
      out.write("            <div class=\"modal-body\">\r\n");
      out.write("                <div class=\"find-modal-body\">\r\n");
      out.write("                    <div class=\"find-id-div\"><button class=\"btn btn-primary find-id-btn\" onclick=\"\">아이디 찾기</button></div>\r\n");
      out.write("                    <div class=\"find-password-div\"><button class=\"btn btn-primary find-password-btn\" onclick=\"\">비밀번호 찾기</button></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"find-area\">\r\n");
      out.write("                </div>\r\n");
      out.write("        \r\n");
      out.write("            <div class=\"find-modal-footer\">\r\n");
      out.write("              <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">닫기</button>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
